name: Update Sitemap

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # Jalankan setiap hari pada pukul 00:00 UTC

jobs:
  update-sitemap:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate Sitemap
        run: |
          echo '<?xml version="1.0" encoding="UTF-8"?>' > sitemap.xml
          echo '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">' >> sitemap.xml
          for file in *.html; do
            [ "$file" == "404.html" ] && continue  # Skip halaman 404
            echo "  <url>" >> sitemap.xml
            echo "    <loc>https://indonewsupdate.github.io/$file</loc>" >> sitemap.xml
            echo "    <lastmod>$(date -u +%Y-%m-%d)</lastmod>" >> sitemap.xml
            echo "    <changefreq>daily</changefreq>" >> sitemap.xml
            echo "    <priority>0.8</priority>" >> sitemap.xml
            echo "  </url>" >> sitemap.xml
          done
          echo '</urlset>' >> sitemap.xml

      - name: Commit & Push Sitemap
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add sitemap.xml
          git commit -m "Update sitemap.xml"
          git push
