name: Update Sitemap

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # Update sitemap setiap hari pada pukul 00:00 UTC (07:00 WIB)

jobs:
  update_sitemap:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt || true  # Jika ada dependency, tambahkan di requirements.txt

      - name: Generate sitemap
        run: python generate_sitemap.py  # Jalankan script untuk membuat sitemap.xml

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add sitemap.xml
          git commit -m "Update sitemap.xml"
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/indonewsupdate/indonewsupdate.github.io.git main
